PPiing/backend

- package-lock.json
- package.json
- src/app.module.e2e-spec.ts
- src/app.module.ts
- src/configs/configuration.ts
- src/configs/typeorm.config.ts
- test/app.e2e-spec.ts
- pg와 typeorm 연동을 위한 config 작성
- 그것이 transcendence니까.!
> docs: :wrench: add configuration file and setting for conneting pg

- src/entities/alarm.entity.ts
- src/entities/chat-participant.entity.ts
- src/entities/chat.entity.ts
- src/entities/friends.entity.ts
- src/entities/game-log.entity.ts
- src/entities/user.entity.ts
- src/enums/alarm-type.enum.ts
- src/enums/chat-type.enum.ts
- src/enums/mastercode/alarm-type.enum.ts
- src/enums/mastercode/chat-type.enum.ts
- src/enums/mastercode/game-option.enum.ts
- src/enums/mastercode/partc-auth.enum.ts
- src/enums/mastercode/relation-status.enum.ts
- src/enums/mastercode/user-status.enum.ts
- src/enums/partc-auth.enum.ts
- src/enums/relation-status.enum.ts
- src/enums/user-status.enum.ts
- src/user/dto/update-user.dto.ts
- ENUM 타입의 문자열을 마스터코드로 변경
- DDL 확인 결과 엔티티에서 ENUM으로 정의하여도 DB엔 정상적으로 varchar 타입으로 삽입되는것 확인하였습니다.
- 변경에 따른 일부 코드 리팩터링
- 일부 default 값 제거
- #21
> :recycle: #21 change ENUM literal

- src/user/user.repository.ts
- src/user/user.service.ts
레포패턴에 맞도록 코드를 리팩터하였습니다.
- 이렇게 하는게 맞을까요?
- 좀더 디자인 패턴에 맞게 수정하자는 의견
> refactor: :recycle: refactor: implement repository pattern

- src/app.module.ts
- src/entities/game-log.entity.ts
- src/entities/game.entity.ts
- src/entities/user.entity.ts
- src/enums/mastercode/game-type.enum.ts
- src/game-log/dto/create-game-log.dto.ts
- src/game-log/dto/create-game.dto.ts
- src/game-log/dto/game-data.ts
- src/game-log/dto/in-game.dto.ts
- src/game-log/dto/meta.dto.ts
- src/game-log/dto/ready.dto.ts
- src/game-log/dto/rule.dto.ts
- src/game-log/dto/spec.dto.ts
- src/game-log/game-log.repository.ts
- src/game-log/game-queue.ts
- src/game-log/game-socket-session.ts
- src/game-log/game.gateway.ts
- src/game-log/game.module.ts
- src/game-log/game.repository.ts
- src/game-log/game.service.ts
- src/game-log/interface/game-session.d.ts
- src/game-log/interface/game-socket.d.ts
- src/game-log/simulation.service.ts
- 기초적인 game module을 추가 했습니다.
- 하지만 랜더링 모듈이 없어서 제대로된 테스트는 되지 않았습니다.
- 프론트작업이 시작되면 같이 맞추면서 개발하면 좋을것 같습니다.
- 테스트 하기 힘들어요 ㅜㅜ
> #25 game module

- src/auth/auth.controller.ts
- Add login redirect url after login
- 핫픽스
> :passport_control: Add login redirect url after login

- .env_sample
- src/auth/auth.controller.ts
- src/auth/ft.strategy.ts
- src/configs/configuration.ts
- src/user/user.service.ts
- FE 팀과 협업하여 로그인 기능을 개선하였습니다.
- 리다이렉트 문제 -> 서버 호스트명이 들어간 절대 경로 기입 대신 상대 경로 기입 방법으로 변경하여 문제 해결
- 헤더 까보니까 Location: ../../../ 이렇게 들어가는데 브라우저가 알아서 잘 리다이렉트 해주는 듯 합니다.
- AUTH_CALLBACKURL 환경변수를 제거하였습니다.
- 환경따라 변할 일이 없고 컨테이너끼리 공유하는 정보도 아니기 때문입니다.
- 기존 사용자 정보가 존재할 때 오류 회피
- #45
> #45 로그인 관련 이슈 수정

- src/game-log/game-log.repository.ts
- src/game-log/game-log.service.spec.ts
#50
- 예전 언급했던 대로 typeorm에서 지원해 주는 메소드를 사용하지 못해 레포지토리까지의 인터페이스까지 유닛 테스트를 작성했습니다.
- .
> feat: :white_check_mark: Add: game service unit test

- src/auth/auth.controller.ts
- src/auth/ft.strategy.ts
- src/auth/session.serializer.ts
- src/user/user.service.ts
- 세션에 여러 정보를 저장하지 않고 db에서 찾을 수 있도록 `seq`만 저장합니다.
- 메모리 점유를 조금만 쓰기 위해서이죠.
> refactor: :recycle: refac: correct Login logic and now save only userSeq in sessionStorage

- src/enums/mastercode/alarm-code.enum.ts
- test/alarm.e2e-spec.ts
- 알람 기능에 대해 간단하게 테스트 케이스들을 만들었습니다.
- 알람 관련하여 알람의 세부 타입을 정의하는 열거형도 정의가 되어 있지 않아 마스터코드와 열거형을 정의하였습니다.
- #63
> feat: #63 add e2e TEST

- src/user/repository/mock/mock.user-profile.repository.ts
- src/user/repository/user-profile.repository.ts
- src/user/user-profile.service.ts
- src/user/user.controller.ts
- test/user.e2e-spec.ts
- 닉네임으로 유저를 검색할 수 있는 검색 기능을 추가하였습니다.
- #67
> feat: #67 add search

- src/game-log/game.gateway.ts
- src/guards/socket.guard.ts
- src/main.ts
- src/session-middleware.ts
- game-log gateway에 패스포트 미들웨어를 적용해 보았습니다.
- 인가 적용을 위해서
> 드디어 소켓통신에도 패스포트 모듈이 적용됩니다.

- package.json
- #91 
- package.json에 `npm run dev` 명령어를 추가 했습니다.
- 백엔드와 프론트 같은 명령어를 위해서 입니다.
> Add: npm dev command

- src/enums/mastercode/game-option.enum.ts
- src/game-log/dto/game-session.dto.ts
- src/game-log/dto/game-socket.dto.ts
- src/game-log/dto/in-game.dto.ts
- src/game-log/dto/meta.dto.ts
- src/game-log/dto/queue.dto.ts
- src/game-log/dto/rule.dto.ts
- src/game-log/dto/spec.dto.ts
- src/game-log/dto/status.dto.ts
- src/game-log/game-queue.ts
- src/game-log/game-socket-session.ts
- src/game-log/game.gateway.ts
- src/game-log/game.service.ts
- src/game-log/interface/game-session.d.ts
- src/game-log/interface/game-socket.d.ts
- src/game-log/simulation.service.ts
- game에서 top과 down 방향으로 지시되던 플레이어가 각각 blue, red로 변경되었습니다.
- dto로 사용되던 interface를 class로 바꾸었고 그에 따라 경로 변경이 있었습니다.
- front와 동기화를 위해 Spec data 변경이 있었습니다.
> Game dto 추가 및 수정, Spec data 변경 및 기타

- src/profile/repository/user-profile.repository.ts
- 검색 결과에서 이미지 URI가 다르게 적용되는 문제를 수정하였어요
- 버그
> fix: profile 이미지 적용 추가수정

- src/profile/profile.module.ts
> fix: remove mockup db @ profile

- src/profile/dto/get-profile.dto.ts
> :bug: profile dto swagger 수정 #113

- src/alarm/alarm.module.e2e-spec.ts
- src/alarm/alarm.module.ts
- src/app.module.e2e-spec.ts
- src/community-bar/friends/friends.controller.ts
- src/community-bar/friends/friends.gateway.ts
- src/community-bar/friends/friends.module.e2e-spec.ts
- src/community-bar/friends/friends.module.ts
- src/community-bar/friends/friends.service.ts
- src/game/game-socket-session.ts
- src/profile/profile.module.e2e-spec.ts
- 친구 요청, 수락, 거절 등 로직 보완 및 
- 알람 모듈과의 연결
- 친구 관련 소켓 생성
#124 => 세부 내용
> :art: friend logic update #124

- src/game/simulation.service.ts
- 함수 내용을 파악하기 힘들게 하는 불필요한 중간 단계를 제거하고 함수를 바로 임포트해서 사용합니다.
- 해당 함수를 참조하는데 불필요한 중간 단계가 있었습니다.
> fix: import check func directly, #127

- src/community-bar/friends/friends.module.ts
- src/profile/profile.module.ts
- 일반 모듈에서 e2e 모듈을 include 하여 발생한 문제를 해결하였습니다.
- #139
> 순환참조 버그 해결

- package-lock.json
- src/game/game.gateway.ts
- src/game/simulation.service.ts
- test를 위해 만든 게임스타트는 레디가 발생하지 않았음.
- 시작하기 전에 레디 이벤트를 발생시킴.
> fix: test start is emit game:ready event

- src/profile/repository/user-profile.repository.ts
- 업로드한 파일의 경로에서 .을 제거하였습니다.
-  #155
> fix: #155 remove dot

- src/entities/user.entity.ts
- src/profile/repository/user-profile.repository.ts
- src/upload/upload.controller.ts
> fix: #155 업로드 경로 수정

- src/auth/auth.controller.ts
- Logout 500 error fix
- 이유 : passport version update 후 logout 함수의 형식이 바뀜
> :bug: logout error fix #153

- src/profile/profile.controller.ts
- src/profile/user-game.service.ts
> typo: userGameService에 geUserGame -> getUserGame으로 변경 #137

- src/game/game-log.service.ts
- src/game/repository/game-log.repository.ts
- src/game/simulation.service.ts
- 레파지토리에 메소드는 작성이 되어있었고,
- 좀 더 이해하기 쉽게 시뮬레이션 서비스가 아닌
- 게임로그 서비스에 관련 로직을 옮겼습니다.
- 이해하기 쉽게
- 테스트
> rename: game-log save method

- src/game/calPosition/calculate.ball.displacement.ts
- src/game/checkBound/check.paddle.bound.ts
- src/game/checkBound/check.wall.bound.ts
- src/game/dto/in-game.dto.ts
- src/game/game.gateway.ts
- src/game/simulation.service.ts
1. ball이 경기장 바깥으로 나감
2. 공이 벽 충돌을 감지하지 않음
3. 블루패들 충돌 감지가 이상함
4. render data를 라운드 해줌.
> Fix game bugs

- package-lock.json
- package.json
- src/game/dto/in-game.dto.ts
- src/game/game-log.service.spec.ts
- src/game/game.gateway.ts
- src/game/game.service.ts
- src/game/gameStatus/playing.ts
- src/game/gameStatus/ready.ts
- src/game/gameStatus/score.ts
- src/game/simulation.service.ts
- `@nestjs/schedule` 을 사용해 다이나믹 인터벌을 적용했습니다.
- 해당 작업을 하다가 스코어 후에 게임 리셋하는 과정에서 잘못된 초기화가 있었습니다. -> 수정완
> refac: interval -> dynamic interval

- src/chatrooms/chatrooms.gateway.ts
- edit data type for socket event
- to match data type
> feat: edit type for socket event(chat:init)

- src/game/game.gateway.ts
-  #179 이슈의 세션 관련 문제를 @jinbekim 님과 해결하였습니다.
-  #179
> fix: #179 session object

- src/auth/auth.controller.ts
- 로그인 시 콜백 URI가 의도대로 동작하도록 변경하였습니다.
- 안정성을 위함
> Fix redirect

- .eslintrc.json
- src/game/dto/game-session.dto.ts
- src/game/game.gateway.ts
- src/game/game.service.ts
- 게임초대 부분 구현을 위해서 게임 생성 부분 로직을 분리했습니다.
- 내용을 적어주세요.
> 게임초대를 위해서 게임생성부분을 분리했습니다.

- src/entities/friends.entity.ts
- src/user/repository/user.repository.ts
- src/user/user.service.ts
> :fix: friend list err fix #187

- src/auth/auth.controller.ts
- 2FA 인증 시 401 error 발생 => 불필요했던 useGuard를 제거하였습니다.
- #197
> :passport_control: 2FA error fix #197

- src/community-bar/friends/friends.controller.ts
- block의 동작이 제대로 되지 않아 프로필 조회시 relation에 대한 정보가 정확하지 않아서 수정하였습니다.
- #198
> :bug: block error fix #198

- src/configs/configuration.ts
> revert configuration

- src/community-bar/friends/friends.controller.ts
- src/community-bar/friends/repository/friends.repository.ts
- 친구 요청, 수락 or 거절 반응에 대한 에러를 수정하였습니다.
(원인 : follower, followee 를 반대로 검색하여 결과에 대한 혼동이 있었습니다.)
- #201
> :bug: friends reaction err fix #201

- src/game/simulation.service.ts
> fix: control paddle direction

- src/game/dto/in-game.dto.ts
- src/game/dto/spec.dto.ts
> fix: paddle velocity

- src/game/simulation.service.ts
> fix: test metadata input

- src/game/calPosition/calculate.paddle.displacement.ts
- src/game/gameStatus/playing.ts
> log: calculated position

- src/game/calPosition/calculate.paddle.displacement.ts
- src/game/dto/in-game.dto.ts
- src/game/gameStatus/playing.ts
> fix: paddle position calculation

- src/community-bar/friends/repository/friends.repository.ts
- 친구 요청 응답에 대한 수락시 친구 목록 동기화가 되지 않는 문제에 대해 수정하였습니다.
- follower, follweee 혼동 때문에 발생된 문제였습니다.
> :bug: friend accept err fix #201

- src/alarm/alarm.service.ts
- src/game/calPosition/calculate.paddle.displacement.ts
- 게임 초대 후 알람 갱신 요청 보내기
- 게임 초대 후 알람 갱신 요청 보내기
> fix: emit refresh alarm after create invite

- src/alarm/alarm.service.ts
- src/game/calPosition/calculate.paddle.displacement.ts
- src/game/gameStatus/playing.ts
> log paddle position

- src/community-bar/friends/friends.gateway.ts
> add: middleware in friends gateway

- src/game/game.gateway.ts
- src/game/simulation.service.ts
> emit test ready

- src/alarm/alarm.service.ts
> check duplicated alarm

- src/configs/configuration.ts
- src/game/calPosition/calculate.ball.velocity.ts
- src/game/checkBound/check.paddle.bound.ts
- src/game/dto/in-game.dto.ts
- src/game/dto/spec.dto.ts
- src/game/game.controller.ts
- src/game/gameStatus/playing.ts
- 공의 바운드가 패들에 부딪힌 각도에 기반해서 변경됩니다.
- 속도를 증가 시켰습니다.
- 내용을 적어주세요.
> feat: ball bound paddle with radian base

- src/game/game.service.ts
- 새로운 게임을 만들때 룰데이터가 존재하지 않아 에러가 발생했습니다.
- 객체를 생성 후에 룰을 적용했습니다.
> fix: apply ruledata when creategame

- src/alarm/alarm.controller.ts
- src/alarm/alarm.service.ts
- src/alarm/repository/alarm.repository.ts
- src/community-bar/friends/friends.service.ts
- 친구 초대를 수락하거나 거절할때 읽음 표시를 합니다.
> fix: alarm read when accept or reject friend request

- src/game/game.gateway.ts
- src/game/simulation.service.ts
- enq로 게임 시작할 수 있게 기존 테스트용 메소드를 조금 수정했습니다.
> now can test enq, deq, and game

- src/alarm/alarm.gateway.ts
- src/alarm/alarm.service.ts
- src/community-bar/friends/friends.gateway.ts
> emit reresh event

- src/game/game.controller.ts
> await reject game

- src/auth/auth.controller.ts
> 메일 코드 체크 - 유즈가드 빼기

- src/game/game-queue.ts
> fix condition

- src/game/game-log.service.ts
> await update game result

- src/game/game-queue.ts
- 큐에서 유저 검색하는 방법을 수정했습니다.
- 내용을 적어주세요.
> queue find with userSeq

- src/auth/auth.controller.ts
- src/auth/auth.service.ts
- src/auth/ft.strategy.ts
- src/auth/mock.strategy.ts
- src/guards/check-login.guard.ts
- src/user/dto/user.dto.ts
- src/user/repository/user.repository.ts
- src/user/user.service.ts
- first login api 구현
- rename is_login -> isLogin
> :sparkles: feat: add first login api & rename is_login #224

- src/game/game.gateway.ts
- src/game/game.service.ts
- src/game/simulation.service.ts
- 테스트용 메소드 제거
- 초대로 게임이 생성될 경우 재참가 불가한 상태로 생성됨
- 그에 따라 둘다 나갔을 경우 메모리상에 계속해서 남아있을까봐 일정 프레임이 넘어가면 게임이 삭제됨.
- 
- 내용을 적어주세요.
> fix: invite user

- src/profile/repository/rank.repository.ts
> amend rank score win and lose

- src/alarm/alarm.service.ts
- src/configs/configuration.ts
- src/game/game.controller.ts
- src/game/game.gateway.ts
- src/game/game.service.ts
> add: gameready listening

- src/status/status.gateway.ts
- src/status/status.service.ts
- OnEvent 내 client 소켓 -> server 소켓으로 변경했습니다
> :bug: fix: client socket to server socket #256

- src/game/game-log.controller.ts
- src/game/game.controller.ts
- src/game/game.service.ts
- src/game/simulation.service.ts
- `game/current` 로 get요청하면
- 현재 진행중인 게임데이터 잔뜩 보내드립니다.
- 내용을 적어주세요.
> add: api currentgamelist

- src/game/game-queue.ts
- enqueue가 중복으로 생기지 않습니다.
- 정상적으로 enqueue할 경우 false혹은 게임데이터를 돌려줍니다.
- 중복요청일 경우 null 리턴을 합니다.
- 내용을 적어주세요.
> fix: enque

- src/game/game.gateway.ts
- src/game/simulation.service.ts
> add: some logger
